POST http://localhost:5292/Chat
Content-Type: application/x-www-form-urlencoded

message=Which bookings do not currently have hotel rooms associated with them?

# curl -d 'message="Which bookings do not currently have hotel rooms associated with them?"' http://localhost:5292/Chat
